import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const {PGlite}=await import('@electric-sql/pglite');
test('Gerçek PostgreSQL: sürüm, onay, revizyon, RLS, bağımlılık ve eski sekme kuralları',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create schema auth;create schema storage;
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
 create function public.aktif_rol() returns text language sql stable as $$ select current_setting('test.role',true) $$;
 create function public.aktif_ad() returns text language sql stable as $$ select 'Ada'::text $$;
 create function public.aktif_personel_adi() returns text language sql stable as $$ select 'Ada'::text $$;
 create function public.ekip_mi() returns boolean language sql stable as $$ select public.aktif_rol() in ('admin','personel') $$;
 create function public.yonetici_mi() returns boolean language sql stable as $$ select public.aktif_rol()='admin' $$;
 create function public.kart_gorunur(kart text) returns boolean language sql stable as $$ select kart='k1' $$;
 create table public.urun_kartlari(id text primary key,marka text);
 create table public.urun_adimlar(id text primary key,kart_id text references urun_kartlari(id),ad text,atanan text,durum text,tarih text,sira int,sure int,gercek_sure int default 0,arsivlendi boolean default false,musteri_adimi boolean default false);
 create table public.urun_dokumanlari(id text primary key,kart_id text references urun_kartlari(id),dosya_adi text,dosya_yolu text,dosya_turu text,boyut_kb int,yukleyen text,yuklenme_tarihi text);
 create table public.urun_adim_notlari(id text primary key,adim_id text,metin text,yazan text,tarih text);
 create table public.bildirimler(id text primary key,alici text,tip text,baslik text,metin text,kart_id text,adim_id text,olusturan text);
 create table storage.objects(id text,bucket_id text,name text);
 insert into urun_kartlari values('k1','Marka'),('k2','Diğer');
 insert into urun_adimlar(id,kart_id,ad,atanan,durum,tarih,sira) values
 ('a','k1','Tasarım','Ada','Tamamlandı','2026-09-09',1),('b','k1','Kontrol','Ada','Bekliyor','2026-09-10',2),('c','k1','Müşteri','Ada','Bekliyor','2026-09-12',3),('x','k2','Gizli','Ada','Bekliyor','2026-09-12',1);
 update urun_adimlar set musteri_adimi=true where id='c';
 insert into storage.objects values('d1','urun-dokumanlari','k1/v1.pdf'),('d2','urun-dokumanlari','k1/v2.pdf');
 grant usage on schema public,auth,storage to authenticated;grant select,update,delete on all tables in schema public to authenticated;
 `);
 await db.exec(fs.readFileSync(new URL('../sql/workflow-v2.sql',import.meta.url),'utf8'));
 await db.exec(`select set_config('test.uid','11111111-1111-1111-1111-111111111111',false);select set_config('test.role','admin',false);set role authenticated;`);
 const rpc=async(islem,veri={})=>(await db.query('select public.workflow_v2($1,$2::jsonb) as result',[islem,JSON.stringify(veri)])).rows[0].result;
 const role=async value=>db.query("select set_config('test.role',$1,false)",[value]);
 assert.equal((await rpc('surum')).surum,2);
 assert.equal((await db.query("select wf_tamamlandi from urun_adimlar where id='a'")).rows[0].wf_tamamlandi,null);
 await rpc('bagimlilik',{adim_id:'b',bagimliliklar:['a']});
 await assert.rejects(rpc('bagimlilik',{adim_id:'a',bagimliliklar:['b']}),/döngü/);
 await assert.rejects(rpc('bagimlilik',{adim_id:'b',bagimliliklar:['x']}),/Aynı kart/);
 await assert.rejects(rpc('durum',{adim_id:'x',durum:'Tamamlandı',onceki_durum:'Bekliyor'}),/erişiminiz/);
 await role('personel');await assert.rejects(rpc('bagimlilik',{adim_id:'b',bagimliliklar:[]}),/yönetici/);await role('admin');
 const doc=await rpc('dokuman',{kart_id:'k1',dosya_adi:'etiket.pdf',dosya_yolu:'k1/v1.pdf',dosya_turu:'pdf',boyut_kb:5});
 assert.equal(doc.wf_surum,1);
 await rpc('bagimlilik',{adim_id:'c',bagimliliklar:['b']});
 const sun={adim_id:'c',dosya_ids:[doc.id],duzeltme_adim_id:'a',revizyon_hedefi:'2099-09-30'};
 await assert.rejects(rpc('sun',sun),/Ön koşullar/);
 await rpc('durum',{adim_id:'b',durum:'Tamamlandı',onceki_durum:'Bekliyor'});
 await assert.rejects(rpc('durum',{adim_id:'b',durum:'RET',onceki_durum:'Bekliyor'}),/başka bir oturum/);
 const paket=await rpc('sun',sun);assert.equal(paket.dosyalar[0].surum,1);
 await assert.rejects(rpc('sun',sun),/Zaten/);
 await assert.rejects(db.query("update urun_adimlar set durum='Tamamlandı' where id='c'"),/Müşteri adımını/);
 await assert.rejects(db.query("update urun_adimlar set wf_bagimliliklar='[]' where id='b'"),/Akış alanları/);
 await assert.rejects(db.query('delete from urun_dokumanlari where id=$1',[doc.id]),/Onaya sunulan/);
 await role('musteri');
 await assert.rejects(rpc('karar',{adim_id:'c',paket_id:paket.id,karar:'revizyon',not:''}),/açıklaması/);
 const karar=await rpc('karar',{adim_id:'c',paket_id:paket.id,karar:'revizyon',not:'Barkod büyüsün'});assert.equal(karar.durum,'RET');
 assert.equal((await db.query('select * from revizyon_turlari')).rows.length,0,'müşteri iç revizyon bilgisi görmez');
 await assert.rejects(rpc('karar',{adim_id:'c',paket_id:paket.id,karar:'onay'}),/güncel değil/);
 await role('admin');
 const reopened=(await db.query("select * from urun_adimlar where id='a'")).rows[0];assert.equal(reopened.durum,'RET');assert.equal(reopened.wf_tamamlandi,null);
 assert.equal((await db.query('select * from revizyon_turlari')).rows.length,1);
 assert.equal((await db.query('select * from bildirimler')).rows.length,1);
 await assert.rejects(rpc('durum',{adim_id:'b',durum:'Devam Ediyor',onceki_durum:'Tamamlandı'}),/Önce bağlı/);
 await rpc('durum',{adim_id:'a',durum:'Devam Ediyor',onceki_durum:'RET'});
 await db.query("update urun_adimlar set gercek_sure=25 where id='a'");
 await rpc('durum',{adim_id:'a',durum:'Tamamlandı',onceki_durum:'Devam Ediyor'});
 await assert.rejects(rpc('sun',sun),/daha yeni sürümü/);
 const v2=await rpc('dokuman',{kart_id:'k1',onceki_id:doc.id,dosya_adi:'etiket-son.pdf',dosya_yolu:'k1/v2.pdf',dosya_turu:'pdf',boyut_kb:8});assert.equal(v2.wf_surum,2);assert.equal(v2.wf_seri,doc.wf_seri);
 await assert.rejects(rpc('sun',sun),/son sürümü/);
 const ikinci=await rpc('sun',{...sun,dosya_ids:[v2.id]});assert.equal(ikinci.tur,2);
 const rev=(await db.query('select * from revizyon_turlari')).rows[0];assert.equal(Number(rev.harcanan_dk),25);assert.ok(rev.yeniden_sunuldu);
 await role('musteri');
 await rpc('karar',{adim_id:'c',paket_id:ikinci.id,karar:'onay'});
 const ps=(await db.query('select * from onay_paketleri order by tur')).rows;assert.equal(ps[0].durum,'Revizyon');assert.equal(ps[1].durum,'Onaylandı');assert.equal(ps[0].dosyalar[0].surum,1);
 await assert.rejects(rpc('durum',{adim_id:'a',durum:'RET',onceki_durum:'Tamamlandı'}),/yalnızca ekip/);
 await db.exec('reset role;set role anon;');await assert.rejects(rpc('surum'),/permission denied/);
 }finally{await db.close();}
});
